name: Model Training CICD
permissions:
  id-token: write
  contents: write

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python app.py
          
          echo "RF and LR Model Score" > report.md
          cat scores.txt
         
          echo "Confusion Matrix & Feature Importance" > report1.md
          echo '|[](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '|[](./FeatureImportance.png "FeatureImportance")' >> report1.md

          git add "iris (1).csv"
          git commit -m "Added dataset file"
          git push origin main

     
          cat report.md report1.md >> combined_file.md
          cml comment create combined_file.md
          
